In [6]:
import numpy as np

In [7]:
numeros = [10,20,30,40,50,60,70]
# lista python simples

In [8]:
np.array(numeros)
# converte a lista pra array numpy

array([10, 20, 30, 40, 50, 60, 70])

In [9]:
mt = [[1,1,1],[2,2,2],[3,3,3],[4,4,4]]
# lista de listas 4x3

In [10]:
np.array(mt)
# vira matriz numpy

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [11]:
np.arange(5,30)
# intervalo de 5 ate 29

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(1,80,3)
# de 1 a 79 pulando de 3

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79])

In [ ]:
np.zeros(8)
# lista de 8 zeros

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
arr = np.zeros(4)

In [38]:
arr
# confere o array de zeros

array([0., 0., 0., 0.])

In [ ]:
arr = np.zeros((3,9))
# matriz de zeros 3x9

In [40]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,3))
# matriz de 1 5x3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(4)
# matriz identidade 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.linspace(0,50,4)
# 4 valores igualmente espacados entre 0 e 50

array([ 0.        , 16.66666667, 33.33333333, 50.        ])

In [23]:
np.random.rand(8)
# 8 numeros aleatorios entre 0 e 1

array([0.21589826, 0.71698019, 0.42534824, 0.6528594 , 0.80072524,
       0.83138025, 0.85211784, 0.71834475])

In [ ]:
np.random.randn(4)
# distribuicao que tende ficar perto de 0

array([ 0.87936407, -0.94810786, -0.41558589,  0.12805155])

In [ ]:
np.random.randint(10,200,12)
# 12 numeros aleatorios entre 10 e 199

array([108,  77, 147, 121,  77,  70,  40, 115,  26, 147,  16, 130],
      dtype=int32)

In [27]:
np.round(np.random.rand(6) * 50, 1)
# arredonda pra 1 casa decimal

array([26.1, 37.1,  4.5, 41.7,  4.8, 36.2])

In [ ]:
nums = np.random.rand(16)
# 16 numeros aleatorios

In [ ]:
nums

array([0.66046609, 0.14941636, 0.34931085, 0.24228663, 0.26466549,
       0.74260771, 0.51828652, 0.21554897, 0.44304583, 0.19247712,
       0.16126645, 0.00908847, 0.16784467, 0.45741335, 0.65025097,
       0.77755902])

In [ ]:
nums.reshape((4,4))
# vira matriz 4x4 so na visualizacao

array([[0.66046609, 0.14941636, 0.34931085, 0.24228663],
       [0.26466549, 0.74260771, 0.51828652, 0.21554897],
       [0.44304583, 0.19247712, 0.16126645, 0.00908847],
       [0.16784467, 0.45741335, 0.65025097, 0.77755902]])

In [ ]:
nums = nums.reshape((4,4))
# agora atribuido a nums grava o reshape na variavel

In [ ]:
nums.shape
# dimensao

(4, 4)

In [33]:
nums.max()
# maior valor da matriz

np.float64(0.7775590160318621)

In [34]:
nums.min()
# menor valor

np.float64(0.00908847447636063)

In [ ]:
nums.argmax()
# posicao do maior valor

np.int64(15)

In [ ]:
nums.argmin()
# posicao do menor valor

np.int64(11)