In [1]:
import numpy as np

In [2]:
minha_lista = [1,2,3]
#cria uma lista

In [ ]:
np.array(minha_lista)
#transforma a lista em um array numpy

array([1, 2, 3])

In [4]:
minha_matriz = [[1,2,3], [4,5,6],[7,8,9]]
#cria matriz 3x3

In [5]:
np.array(minha_matriz)
#transforma a matriz em um array numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)
#cria um intervalo de 0 a 10 nao incluido o 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10, 2)
#cria um intervalo de 0 a 10 nao incluido o 10, pulando o numeros impares

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)
#cria um array de zeros

array([0., 0., 0.])

In [10]:
arr = np.zeros(3)

In [ ]:
arr
#mostra o array

array([0., 0., 0.])

In [ ]:
arr = np.zeros((5,5))
#cria uma matriz 5x5 de zeros a partir de uma tupla

In [14]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,3))
#matriz 3x3 com numeros 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(4)
# matriz binaria 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.linspace(0,10,2)
#array com 2 numeros com espaçamento igual

array([ 0., 10.])

In [18]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.random.rand(5)
#cria 5 numeros aleatorios

array([0.66258596, 0.54316263, 0.3318308 , 0.95051545, 0.17928303])

In [21]:
np.random.randn(4)
# cria 4 numeros aleatorios em um intervalo (valores proximos a zero aparecem mais do que os distantes)

array([ 0.0271475 , -0.44407925, -2.09045207,  0.17977664])

In [24]:
np.random.randint(0,100,10)
# cria 10 numeros aleatorios inteiros dentro do intervalo 0-99

array([27, 67, 87, 29, 24, 69,  9, 53, 88, 64], dtype=int32)

In [26]:
np.random.rand(5) * 100

array([30.59208552, 16.11113191, 56.20777841, 86.72257968, 61.03102398])

In [28]:
np.round(np.random.rand(5) * 100, 0)

array([ 1., 26.,  7., 28., 55.])

In [ ]:
arr = np.random.rand(25)
#gera 25 numeros aleatorios

In [31]:
arr

array([0.6663904 , 0.12719865, 0.01960484, 0.48891472, 0.74896424,
       0.5004237 , 0.82638002, 0.68940713, 0.2867251 , 0.65205082,
       0.23482647, 0.01208757, 0.28969002, 0.44192549, 0.03799041,
       0.27527014, 0.28039848, 0.03701177, 0.02408961, 0.47576527,
       0.9468972 , 0.62844572, 0.60033723, 0.87893442, 0.91820859])

In [ ]:
arr.reshape((5,5))
# reformata para um array bidimensional, ou seja uma matriz 5x5
# so faz na memoria e apaga

array([[0.6663904 , 0.12719865, 0.01960484, 0.48891472, 0.74896424],
       [0.5004237 , 0.82638002, 0.68940713, 0.2867251 , 0.65205082],
       [0.23482647, 0.01208757, 0.28969002, 0.44192549, 0.03799041],
       [0.27527014, 0.28039848, 0.03701177, 0.02408961, 0.47576527],
       [0.9468972 , 0.62844572, 0.60033723, 0.87893442, 0.91820859]])

In [33]:
arr = arr.reshape((5,5))
# atribui ao arr o reshape

In [ ]:
arr.shape
# tamanho do arr

(5, 5)

In [36]:
arr.max()
#encontra o maior numero

np.float64(0.9468971975819399)

In [37]:
arr.min()
#encontra o menor numero

np.float64(0.012087569025337697)

In [38]:
arr.argmax()
# retorna o indice do maior valor

np.int64(20)

In [39]:
arr.argmin()
# retorna o indice do menor valor

np.int64(11)