In [1]:
import numpy as np

In [ ]:
arr = np.arange(0,30,3)
# gera um array de 0 a 30 com um interalo de 3

In [3]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
arr[3]
#mostra o indice 3 do array

np.int64(9)

In [ ]:
arr[2:5]
#corta os ois primeiro numeros e os 5 ultimos sendo que o ultimo nao conta

array([ 6,  9, 12])

In [ ]:
arr[:5]
# corta os ultimos 4 numeros

array([ 0,  3,  6,  9, 12])

In [ ]:
arr[2:]
#corta os dois primeiros numeros

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
arr[2:] = 100
# todos os numeros menos os dois primeiros recebem 100 como valor

In [9]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr = np.arange(50).reshape((5,10))
# faz ele como uma matriz 5x10

In [12]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr.shape
#mostra o tamanho dele

(5, 10)

In [ ]:
arr2 = arr[:3] 
# arr2 aponta para as 3 primeiras linhas, podendo ter mas um sllice [] para as colunas, como nao ha entao pega todas 

In [23]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [ ]:
arr2[:] = 100
# todas as linhas e colunas do arr2 recebem 100

In [ ]:
arr2 = arr[:3]
# arr2 aponta para as tres primeiras linhas e todas as colunas de arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
arr2 = arr[:3].copy()
#agora arr2 tem os dados, nao aponta maias para arr

In [ ]:
bol = arr > 50
# pega todos os indices que sao maiores que 50

In [30]:
arr[bol]
# mostra todos os valores dos  indices de bol

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [ ]:
array = np.linspace(0,100,30)
#cria um array

In [ ]:
array.shape
# array de uma dimensao

(30,)

In [38]:
array = array.reshape(3,10)
#array de 2 dimensoes

In [39]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [ ]:
array[0:2,2]
# pega os dois elementos das duas primeiras linhas da coluna de indice 2

array([ 6.89655172, 41.37931034])