In [1]:
import numpy as np

In [3]:
arr = np.arange(0,16)
# cria um array de 0 a 15

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr + arr
# soma os dois arrays (tem que ser do mesmo tamanho)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
arr - arr
# subtrai dois arrays(tem que ser do mesmo tamanho)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr * arr
# multiplica os dois arrays

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [ ]:
arr / arr
# divide os dois arrays, causa o primeiro nan pois o primeiro numero e 0

C:\Users\Matheus\AppData\Local\Temp\ipykernel_7040\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [9]:
1 / arr

C:\Users\Matheus\AppData\Local\Temp\ipykernel_7040\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [ ]:
arr **2
# arr elevado ao quadrado

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [11]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [12]:
arr -100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [13]:
arr *100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [16]:
np.sqrt(arr)
# raiz quadrada do array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [ ]:
np.std(arr)
# calcula o desvio padrao do array

np.float64(4.6097722286464435)

In [ ]:
np.sin(arr)
# calcula o seno do array

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [21]:
np.max(arr)
# pega o maior valor do array

np.int64(15)

In [22]:
np.min(arr)
# peega o menor valor do array

np.int64(0)